# -*- coding: utf-8 -*-
import FreeCAD, Mesh, tempfile, subprocess
from PySide import QtCore,QtGui

import macrooptions
reload(macrooptions)

doc=App.ActiveDocument
if doc is None:
	message="No document open"
	dialog=QtGui.QMessageBox(QtGui.QMessageBox.Information,'Error',message)
	dialog.setWindowModality(QtCore.Qt.ApplicationModal)
	dialog.exec_()

else:
	visibleObjs=[]

	for obj in doc.Objects:
		if obj.ViewObject.isVisible():
			visibleObjs.append(obj)

	f=tempfile.NamedTemporaryFile(suffix=".stl")
	fileName=f.name
	f.close()

	print "will export to "+fileName
	Mesh.export(visibleObjs,fileName)

	subprocess.Popen([macrooptions.SLICER,fileName])
